
language: ruby

rvm:
- 2.0.0
- 2.1.0
- 2.2.0
#- jruby-19mode # JRuby in 1.9 mode
#- rbx-2.1.1

env:
- DB=mysql
#- DB=pgsql
#- DB=sqlite

gemfile:
- Gemfile

before_install:
- gem update --system
- gem --version
- sh -c "echo 'hello'"

before_script:
- gem update --system
- gem --version
- chmod -R 664 Gemfile
- cp ./README.md ./readme.txt


script: 
- rake minitest

notifications:
  emails:
    - krakenbeal@gmail.com
#   - foo@example.com
  on_success: change # default: change
  on_failure: change

