
language: ruby

rvm:
- 2.1.0
- 2.0.0
- 1.9.3
#- jruby-18mode # JRuby in 1.8 mode
#- jruby-19mode # JRuby in 1.9 mode
#- rbx-2.1.1
#- 1.8.7

env:
- DB=mysql
#- DB=pgsql
#- DB=sqlite

gemfile:
- Gemfile

before_install:
- gem update --system
- gem --version
- sh -c "echo 'hello'"

before_script:
- gem update --system
- gem --version
- chmod -R 664 Gemfile
- cp ./Readme ./readme.txt

script: 
- rake

notifications:
  emails:
    - krakenbeal@gmail.com
#   - foo@example.com
  on_success: always # default: change
  on_failure: always

